site_name: COMP423 Course Notes
theme:
  name: material
  features: 
    - content.code.select
    - content.code.copy

# Code Blocks
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# Admonitions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
