site_name: COMP423 Course Notes
theme:
  name: material

# Code Blocks
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
features:
  - content.code.copy
theme:
features:
  - content.code.annotate

# Admonitions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
theme:
  icon:
    admonition:
      <type>: <icon>